// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/blocklist.proto

package blocklistmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item represents block list item entity.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Jid           string                 `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_model_v1_blocklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_blocklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_blocklist_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Item) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

// Items represent a set of block list items.
type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_proto_model_v1_blocklist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_blocklist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_blocklist_proto_rawDescGZIP(), []int{1}
}

func (x *Items) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_model_v1_blocklist_proto protoreflect.FileDescriptor

const file_proto_model_v1_blocklist_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/model/v1/blocklist.proto\x12\x12model.blocklist.v1\"4\n" +
	"\x04Item\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03jid\x18\x02 \x01(\tR\x03jid\"7\n" +
	"\x05Items\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.model.blocklist.v1.ItemR\x05itemsB%Z#pkg/model/blocklist/;blocklistmodelb\x06proto3"

var (
	file_proto_model_v1_blocklist_proto_rawDescOnce sync.Once
	file_proto_model_v1_blocklist_proto_rawDescData []byte
)

func file_proto_model_v1_blocklist_proto_rawDescGZIP() []byte {
	file_proto_model_v1_blocklist_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_blocklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_blocklist_proto_rawDesc), len(file_proto_model_v1_blocklist_proto_rawDesc)))
	})
	return file_proto_model_v1_blocklist_proto_rawDescData
}

var file_proto_model_v1_blocklist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_v1_blocklist_proto_goTypes = []any{
	(*Item)(nil),  // 0: model.blocklist.v1.Item
	(*Items)(nil), // 1: model.blocklist.v1.Items
}
var file_proto_model_v1_blocklist_proto_depIdxs = []int32{
	0, // 0: model.blocklist.v1.Items.items:type_name -> model.blocklist.v1.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_model_v1_blocklist_proto_init() }
func file_proto_model_v1_blocklist_proto_init() {
	if File_proto_model_v1_blocklist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_blocklist_proto_rawDesc), len(file_proto_model_v1_blocklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_blocklist_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_blocklist_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_blocklist_proto_msgTypes,
	}.Build()
	File_proto_model_v1_blocklist_proto = out.File
	file_proto_model_v1_blocklist_proto_goTypes = nil
	file_proto_model_v1_blocklist_proto_depIdxs = nil
}
