// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/user.proto

package usermodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user entity.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Scram         *Scram                 `protobuf:"bytes,2,opt,name=scram,proto3" json:"scram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_model_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetScram() *Scram {
	if x != nil {
		return x.Scram
	}
	return nil
}

type Scram struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sha1           string                 `protobuf:"bytes,1,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Sha256         string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Sha512         string                 `protobuf:"bytes,3,opt,name=sha512,proto3" json:"sha512,omitempty"`
	Sha3512        string                 `protobuf:"bytes,4,opt,name=sha3512,proto3" json:"sha3512,omitempty"`
	IterationCount int64                  `protobuf:"varint,5,opt,name=iteration_count,json=iterationCount,proto3" json:"iteration_count,omitempty"`
	Salt           string                 `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	PepperId       string                 `protobuf:"bytes,7,opt,name=pepper_id,json=pepperId,proto3" json:"pepper_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Scram) Reset() {
	*x = Scram{}
	mi := &file_proto_model_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scram) ProtoMessage() {}

func (x *Scram) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scram.ProtoReflect.Descriptor instead.
func (*Scram) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *Scram) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *Scram) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Scram) GetSha512() string {
	if x != nil {
		return x.Sha512
	}
	return ""
}

func (x *Scram) GetSha3512() string {
	if x != nil {
		return x.Sha3512
	}
	return ""
}

func (x *Scram) GetIterationCount() int64 {
	if x != nil {
		return x.IterationCount
	}
	return 0
}

func (x *Scram) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *Scram) GetPepperId() string {
	if x != nil {
		return x.PepperId
	}
	return ""
}

var File_proto_model_v1_user_proto protoreflect.FileDescriptor

const file_proto_model_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x19proto/model/v1/user.proto\x12\rmodel.user.v1\"N\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12*\n" +
	"\x05scram\x18\x02 \x01(\v2\x14.model.user.v1.ScramR\x05scram\"\xbf\x01\n" +
	"\x05Scram\x12\x12\n" +
	"\x04sha1\x18\x01 \x01(\tR\x04sha1\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06sha512\x18\x03 \x01(\tR\x06sha512\x12\x18\n" +
	"\asha3512\x18\x04 \x01(\tR\asha3512\x12'\n" +
	"\x0fiteration_count\x18\x05 \x01(\x03R\x0eiterationCount\x12\x12\n" +
	"\x04salt\x18\x06 \x01(\tR\x04salt\x12\x1b\n" +
	"\tpepper_id\x18\a \x01(\tR\bpepperIdB\x1bZ\x19pkg/model/user/;usermodelb\x06proto3"

var (
	file_proto_model_v1_user_proto_rawDescOnce sync.Once
	file_proto_model_v1_user_proto_rawDescData []byte
)

func file_proto_model_v1_user_proto_rawDescGZIP() []byte {
	file_proto_model_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_user_proto_rawDesc), len(file_proto_model_v1_user_proto_rawDesc)))
	})
	return file_proto_model_v1_user_proto_rawDescData
}

var file_proto_model_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_v1_user_proto_goTypes = []any{
	(*User)(nil),  // 0: model.user.v1.User
	(*Scram)(nil), // 1: model.user.v1.Scram
}
var file_proto_model_v1_user_proto_depIdxs = []int32{
	1, // 0: model.user.v1.User.scram:type_name -> model.user.v1.Scram
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_model_v1_user_proto_init() }
func file_proto_model_v1_user_proto_init() {
	if File_proto_model_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_user_proto_rawDesc), len(file_proto_model_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_user_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_user_proto_msgTypes,
	}.Build()
	File_proto_model_v1_user_proto = out.File
	file_proto_model_v1_user_proto_goTypes = nil
	file_proto_model_v1_user_proto_depIdxs = nil
}
