// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/cluster/v1/cluster.proto

package pb

import (
	stravaganza "github.com/jackal-xmpp/stravaganza"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamErrorReason is an enumerated type that describes stream error reason.
type StreamErrorReason int32

const (
	StreamErrorReason_STREAM_ERROR_REASON_INVALID_XML              StreamErrorReason = 0  // Invalid XML.
	StreamErrorReason_STREAM_ERROR_REASON_INVALID_NAMESPACE        StreamErrorReason = 1  // Invalid namespace.
	StreamErrorReason_STREAM_ERROR_REASON_HOST_UNKNOWN             StreamErrorReason = 2  // Host unknown.
	StreamErrorReason_STREAM_ERROR_REASON_CONFLICT                 StreamErrorReason = 3  // Conflict.
	StreamErrorReason_STREAM_ERROR_REASON_INVALID_FROM             StreamErrorReason = 4  // Invalid from.
	StreamErrorReason_STREAM_ERROR_REASON_POLICY_VIOLATION         StreamErrorReason = 5  // Policy violation.
	StreamErrorReason_STREAM_ERROR_REASON_REMOTE_CONNECTION_FAILED StreamErrorReason = 6  // Remote connection failed.
	StreamErrorReason_STREAM_ERROR_REASON_CONNECTION_TIMEOUT       StreamErrorReason = 7  // Connection timeout.
	StreamErrorReason_STREAM_ERROR_REASON_UNSUPPORTED_STANZA_TYPE  StreamErrorReason = 8  // Unsupported stanza type.
	StreamErrorReason_STREAM_ERROR_REASON_UNSUPPORTED_VERSION      StreamErrorReason = 9  // Unsupported version.
	StreamErrorReason_STREAM_ERROR_REASON_NOT_AUTHORIZED           StreamErrorReason = 10 // Not authorized.
	StreamErrorReason_STREAM_ERROR_REASON_RESOURCE_CONSTRAINT      StreamErrorReason = 11 // Resource constraint.
	StreamErrorReason_STREAM_ERROR_REASON_SYSTEM_SHUTDOWN          StreamErrorReason = 12 // System shutdown.
	StreamErrorReason_STREAM_ERROR_REASON_UNDEFINED_CONDITION      StreamErrorReason = 13 // Undefined condition.
	StreamErrorReason_STREAM_ERROR_REASON_INTERNAL_SERVER_ERROR    StreamErrorReason = 14 // Server error.
)

// Enum value maps for StreamErrorReason.
var (
	StreamErrorReason_name = map[int32]string{
		0:  "STREAM_ERROR_REASON_INVALID_XML",
		1:  "STREAM_ERROR_REASON_INVALID_NAMESPACE",
		2:  "STREAM_ERROR_REASON_HOST_UNKNOWN",
		3:  "STREAM_ERROR_REASON_CONFLICT",
		4:  "STREAM_ERROR_REASON_INVALID_FROM",
		5:  "STREAM_ERROR_REASON_POLICY_VIOLATION",
		6:  "STREAM_ERROR_REASON_REMOTE_CONNECTION_FAILED",
		7:  "STREAM_ERROR_REASON_CONNECTION_TIMEOUT",
		8:  "STREAM_ERROR_REASON_UNSUPPORTED_STANZA_TYPE",
		9:  "STREAM_ERROR_REASON_UNSUPPORTED_VERSION",
		10: "STREAM_ERROR_REASON_NOT_AUTHORIZED",
		11: "STREAM_ERROR_REASON_RESOURCE_CONSTRAINT",
		12: "STREAM_ERROR_REASON_SYSTEM_SHUTDOWN",
		13: "STREAM_ERROR_REASON_UNDEFINED_CONDITION",
		14: "STREAM_ERROR_REASON_INTERNAL_SERVER_ERROR",
	}
	StreamErrorReason_value = map[string]int32{
		"STREAM_ERROR_REASON_INVALID_XML":              0,
		"STREAM_ERROR_REASON_INVALID_NAMESPACE":        1,
		"STREAM_ERROR_REASON_HOST_UNKNOWN":             2,
		"STREAM_ERROR_REASON_CONFLICT":                 3,
		"STREAM_ERROR_REASON_INVALID_FROM":             4,
		"STREAM_ERROR_REASON_POLICY_VIOLATION":         5,
		"STREAM_ERROR_REASON_REMOTE_CONNECTION_FAILED": 6,
		"STREAM_ERROR_REASON_CONNECTION_TIMEOUT":       7,
		"STREAM_ERROR_REASON_UNSUPPORTED_STANZA_TYPE":  8,
		"STREAM_ERROR_REASON_UNSUPPORTED_VERSION":      9,
		"STREAM_ERROR_REASON_NOT_AUTHORIZED":           10,
		"STREAM_ERROR_REASON_RESOURCE_CONSTRAINT":      11,
		"STREAM_ERROR_REASON_SYSTEM_SHUTDOWN":          12,
		"STREAM_ERROR_REASON_UNDEFINED_CONDITION":      13,
		"STREAM_ERROR_REASON_INTERNAL_SERVER_ERROR":    14,
	}
)

func (x StreamErrorReason) Enum() *StreamErrorReason {
	p := new(StreamErrorReason)
	*p = x
	return p
}

func (x StreamErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (StreamErrorReason) Type() protoreflect.EnumType {
	return &file_proto_cluster_v1_cluster_proto_enumTypes[0]
}

func (x StreamErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamErrorReason.Descriptor instead.
func (StreamErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

// LocalRouteRequest is the parameter message for LocalRouter Route rpc.
type LocalRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username name of the user to which the stanza is routed to.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// resource is the registered resource to which the stanza is routed to.
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// stanza contains the routed XMPP stanza.
	Stanza        *stravaganza.PBElement `protobuf:"bytes,3,opt,name=stanza,proto3" json:"stanza,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRouteRequest) Reset() {
	*x = LocalRouteRequest{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRouteRequest) ProtoMessage() {}

func (x *LocalRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRouteRequest.ProtoReflect.Descriptor instead.
func (*LocalRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *LocalRouteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LocalRouteRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LocalRouteRequest) GetStanza() *stravaganza.PBElement {
	if x != nil {
		return x.Stanza
	}
	return nil
}

// LocalRouteResponse is the response returned by LocalRouter Route rpc.
type LocalRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRouteResponse) Reset() {
	*x = LocalRouteResponse{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRouteResponse) ProtoMessage() {}

func (x *LocalRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRouteResponse.ProtoReflect.Descriptor instead.
func (*LocalRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

// LocalDisconnectRequest is the parameter message for LocalRouter Disconnect rpc.
type LocalDisconnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the JID node value for the session we wish to disconnect.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// resource is the JID resourcepart value for the session we wish to disconnect.
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// StreamError is disconnection stream error.
	StreamError   *StreamError `protobuf:"bytes,3,opt,name=stream_error,json=streamError,proto3" json:"stream_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDisconnectRequest) Reset() {
	*x = LocalDisconnectRequest{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDisconnectRequest) ProtoMessage() {}

func (x *LocalDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDisconnectRequest.ProtoReflect.Descriptor instead.
func (*LocalDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *LocalDisconnectRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LocalDisconnectRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LocalDisconnectRequest) GetStreamError() *StreamError {
	if x != nil {
		return x.StreamError
	}
	return nil
}

// LocalDisconnectResponse is the response returned by LocalRouter Disconnect rpc.
type LocalDisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDisconnectResponse) Reset() {
	*x = LocalDisconnectResponse{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDisconnectResponse) ProtoMessage() {}

func (x *LocalDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDisconnectResponse.ProtoReflect.Descriptor instead.
func (*LocalDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

// ComponentRouteRequest is the parameter message for ComponentRouter Route rpc.
type ComponentRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stanza contains the routed XMPP stanza.
	Stanza        *stravaganza.PBElement `protobuf:"bytes,1,opt,name=stanza,proto3" json:"stanza,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentRouteRequest) Reset() {
	*x = ComponentRouteRequest{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentRouteRequest) ProtoMessage() {}

func (x *ComponentRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentRouteRequest.ProtoReflect.Descriptor instead.
func (*ComponentRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ComponentRouteRequest) GetStanza() *stravaganza.PBElement {
	if x != nil {
		return x.Stanza
	}
	return nil
}

// ComponentRouteResponse is the response returned by ComponentRouter Route rpc.
type ComponentRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentRouteResponse) Reset() {
	*x = ComponentRouteResponse{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentRouteResponse) ProtoMessage() {}

func (x *ComponentRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentRouteResponse.ProtoReflect.Descriptor instead.
func (*ComponentRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

// StreamError represents a stream disconnection error reason.
type StreamError struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reason             StreamErrorReason      `protobuf:"varint,1,opt,name=reason,proto3,enum=cluster.v1.StreamErrorReason" json:"reason,omitempty"`
	Lang               string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Text               string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ApplicationElement *stravaganza.PBElement `protobuf:"bytes,4,opt,name=applicationElement,proto3" json:"applicationElement,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *StreamError) GetReason() StreamErrorReason {
	if x != nil {
		return x.Reason
	}
	return StreamErrorReason_STREAM_ERROR_REASON_INVALID_XML
}

func (x *StreamError) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *StreamError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StreamError) GetApplicationElement() *stravaganza.PBElement {
	if x != nil {
		return x.ApplicationElement
	}
	return nil
}

// TransferQueueRequest is the parameter message for StreamManagement TransferQueue rpc.
type TransferQueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifier is the queue identifier we want to transmit.
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferQueueRequest) Reset() {
	*x = TransferQueueRequest{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferQueueRequest) ProtoMessage() {}

func (x *TransferQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferQueueRequest.ProtoReflect.Descriptor instead.
func (*TransferQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *TransferQueueRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// QueueElement represents a stream queue element.
type QueueElement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stanza contains the element XMPP stanza.
	Stanza *stravaganza.PBElement `protobuf:"bytes,1,opt,name=stanza,proto3" json:"stanza,omitempty"`
	// h contains the incremental value associated to this element.
	H             uint32 `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueElement) Reset() {
	*x = QueueElement{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueElement) ProtoMessage() {}

func (x *QueueElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueElement.ProtoReflect.Descriptor instead.
func (*QueueElement) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *QueueElement) GetStanza() *stravaganza.PBElement {
	if x != nil {
		return x.Stanza
	}
	return nil
}

func (x *QueueElement) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

// TransferQueueResponse is the response returned by StreamManagement TransferQueue rpc.
type TransferQueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// elements contains all queue elements.
	Elements []*QueueElement `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	// nonce is the queue nonce value.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// inH is the queue incoming h value.
	InH uint32 `protobuf:"varint,3,opt,name=inH,proto3" json:"inH,omitempty"`
	// outH is the queue outgoing h value.
	OutH          uint32 `protobuf:"varint,4,opt,name=outH,proto3" json:"outH,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferQueueResponse) Reset() {
	*x = TransferQueueResponse{}
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferQueueResponse) ProtoMessage() {}

func (x *TransferQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferQueueResponse.ProtoReflect.Descriptor instead.
func (*TransferQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *TransferQueueResponse) GetElements() []*QueueElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *TransferQueueResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TransferQueueResponse) GetInH() uint32 {
	if x != nil {
		return x.InH
	}
	return 0
}

func (x *TransferQueueResponse) GetOutH() uint32 {
	if x != nil {
		return x.OutH
	}
	return 0
}

var File_proto_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_proto_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/cluster/v1/cluster.proto\x12\n" +
	"cluster.v1\x1a4github.com/jackal-xmpp/stravaganza/stravaganza.proto\"{\n" +
	"\x11LocalRouteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12.\n" +
	"\x06stanza\x18\x03 \x01(\v2\x16.stravaganza.PBElementR\x06stanza\"\x14\n" +
	"\x12LocalRouteResponse\"\x8c\x01\n" +
	"\x16LocalDisconnectRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12:\n" +
	"\fstream_error\x18\x03 \x01(\v2\x17.cluster.v1.StreamErrorR\vstreamError\"\x19\n" +
	"\x17LocalDisconnectResponse\"G\n" +
	"\x15ComponentRouteRequest\x12.\n" +
	"\x06stanza\x18\x01 \x01(\v2\x16.stravaganza.PBElementR\x06stanza\"\x18\n" +
	"\x16ComponentRouteResponse\"\xb4\x01\n" +
	"\vStreamError\x125\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1d.cluster.v1.StreamErrorReasonR\x06reason\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12F\n" +
	"\x12applicationElement\x18\x04 \x01(\v2\x16.stravaganza.PBElementR\x12applicationElement\"6\n" +
	"\x14TransferQueueRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"L\n" +
	"\fQueueElement\x12.\n" +
	"\x06stanza\x18\x01 \x01(\v2\x16.stravaganza.PBElementR\x06stanza\x12\f\n" +
	"\x01h\x18\x02 \x01(\rR\x01h\"\x89\x01\n" +
	"\x15TransferQueueResponse\x124\n" +
	"\belements\x18\x01 \x03(\v2\x18.cluster.v1.QueueElementR\belements\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x10\n" +
	"\x03inH\x18\x03 \x01(\rR\x03inH\x12\x12\n" +
	"\x04outH\x18\x04 \x01(\rR\x04outH*\x91\x05\n" +
	"\x11StreamErrorReason\x12#\n" +
	"\x1fSTREAM_ERROR_REASON_INVALID_XML\x10\x00\x12)\n" +
	"%STREAM_ERROR_REASON_INVALID_NAMESPACE\x10\x01\x12$\n" +
	" STREAM_ERROR_REASON_HOST_UNKNOWN\x10\x02\x12 \n" +
	"\x1cSTREAM_ERROR_REASON_CONFLICT\x10\x03\x12$\n" +
	" STREAM_ERROR_REASON_INVALID_FROM\x10\x04\x12(\n" +
	"$STREAM_ERROR_REASON_POLICY_VIOLATION\x10\x05\x120\n" +
	",STREAM_ERROR_REASON_REMOTE_CONNECTION_FAILED\x10\x06\x12*\n" +
	"&STREAM_ERROR_REASON_CONNECTION_TIMEOUT\x10\a\x12/\n" +
	"+STREAM_ERROR_REASON_UNSUPPORTED_STANZA_TYPE\x10\b\x12+\n" +
	"'STREAM_ERROR_REASON_UNSUPPORTED_VERSION\x10\t\x12&\n" +
	"\"STREAM_ERROR_REASON_NOT_AUTHORIZED\x10\n" +
	"\x12+\n" +
	"'STREAM_ERROR_REASON_RESOURCE_CONSTRAINT\x10\v\x12'\n" +
	"#STREAM_ERROR_REASON_SYSTEM_SHUTDOWN\x10\f\x12+\n" +
	"'STREAM_ERROR_REASON_UNDEFINED_CONDITION\x10\r\x12-\n" +
	")STREAM_ERROR_REASON_INTERNAL_SERVER_ERROR\x10\x0e2\xac\x01\n" +
	"\vLocalRouter\x12F\n" +
	"\x05Route\x12\x1d.cluster.v1.LocalRouteRequest\x1a\x1e.cluster.v1.LocalRouteResponse\x12U\n" +
	"\n" +
	"Disconnect\x12\".cluster.v1.LocalDisconnectRequest\x1a#.cluster.v1.LocalDisconnectResponse2a\n" +
	"\x0fComponentRouter\x12N\n" +
	"\x05Route\x12!.cluster.v1.ComponentRouteRequest\x1a\".cluster.v1.ComponentRouteResponse2h\n" +
	"\x10StreamManagement\x12T\n" +
	"\rTransferQueue\x12 .cluster.v1.TransferQueueRequest\x1a!.cluster.v1.TransferQueueResponseB\x10Z\x0epkg/cluster/pbb\x06proto3"

var (
	file_proto_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_proto_cluster_v1_cluster_proto_rawDescData []byte
)

func file_proto_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_proto_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_proto_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cluster_v1_cluster_proto_rawDesc), len(file_proto_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_proto_cluster_v1_cluster_proto_rawDescData
}

var file_proto_cluster_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cluster_v1_cluster_proto_goTypes = []any{
	(StreamErrorReason)(0),          // 0: cluster.v1.StreamErrorReason
	(*LocalRouteRequest)(nil),       // 1: cluster.v1.LocalRouteRequest
	(*LocalRouteResponse)(nil),      // 2: cluster.v1.LocalRouteResponse
	(*LocalDisconnectRequest)(nil),  // 3: cluster.v1.LocalDisconnectRequest
	(*LocalDisconnectResponse)(nil), // 4: cluster.v1.LocalDisconnectResponse
	(*ComponentRouteRequest)(nil),   // 5: cluster.v1.ComponentRouteRequest
	(*ComponentRouteResponse)(nil),  // 6: cluster.v1.ComponentRouteResponse
	(*StreamError)(nil),             // 7: cluster.v1.StreamError
	(*TransferQueueRequest)(nil),    // 8: cluster.v1.TransferQueueRequest
	(*QueueElement)(nil),            // 9: cluster.v1.QueueElement
	(*TransferQueueResponse)(nil),   // 10: cluster.v1.TransferQueueResponse
	(*stravaganza.PBElement)(nil),   // 11: stravaganza.PBElement
}
var file_proto_cluster_v1_cluster_proto_depIdxs = []int32{
	11, // 0: cluster.v1.LocalRouteRequest.stanza:type_name -> stravaganza.PBElement
	7,  // 1: cluster.v1.LocalDisconnectRequest.stream_error:type_name -> cluster.v1.StreamError
	11, // 2: cluster.v1.ComponentRouteRequest.stanza:type_name -> stravaganza.PBElement
	0,  // 3: cluster.v1.StreamError.reason:type_name -> cluster.v1.StreamErrorReason
	11, // 4: cluster.v1.StreamError.applicationElement:type_name -> stravaganza.PBElement
	11, // 5: cluster.v1.QueueElement.stanza:type_name -> stravaganza.PBElement
	9,  // 6: cluster.v1.TransferQueueResponse.elements:type_name -> cluster.v1.QueueElement
	1,  // 7: cluster.v1.LocalRouter.Route:input_type -> cluster.v1.LocalRouteRequest
	3,  // 8: cluster.v1.LocalRouter.Disconnect:input_type -> cluster.v1.LocalDisconnectRequest
	5,  // 9: cluster.v1.ComponentRouter.Route:input_type -> cluster.v1.ComponentRouteRequest
	8,  // 10: cluster.v1.StreamManagement.TransferQueue:input_type -> cluster.v1.TransferQueueRequest
	2,  // 11: cluster.v1.LocalRouter.Route:output_type -> cluster.v1.LocalRouteResponse
	4,  // 12: cluster.v1.LocalRouter.Disconnect:output_type -> cluster.v1.LocalDisconnectResponse
	6,  // 13: cluster.v1.ComponentRouter.Route:output_type -> cluster.v1.ComponentRouteResponse
	10, // 14: cluster.v1.StreamManagement.TransferQueue:output_type -> cluster.v1.TransferQueueResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_cluster_v1_cluster_proto_init() }
func file_proto_cluster_v1_cluster_proto_init() {
	if File_proto_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cluster_v1_cluster_proto_rawDesc), len(file_proto_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_proto_cluster_v1_cluster_proto_depIdxs,
		EnumInfos:         file_proto_cluster_v1_cluster_proto_enumTypes,
		MessageInfos:      file_proto_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_proto_cluster_v1_cluster_proto = out.File
	file_proto_cluster_v1_cluster_proto_goTypes = nil
	file_proto_cluster_v1_cluster_proto_depIdxs = nil
}
