// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/c2s/v1/resourceinfo.proto

package pb

import (
	stravaganza "github.com/jackal-xmpp/stravaganza"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceInfo represents resource associated info content.
type ResourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id indicates what instance registered this resource.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// domain is the resource associated domain.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// info is the resource additional context info.
	Info map[string]string `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// presence is the resource last received presence.
	Presence      *stravaganza.PBElement `protobuf:"bytes,4,opt,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_proto_c2s_v1_resourceinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_c2s_v1_resourceinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_proto_c2s_v1_resourceinfo_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ResourceInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ResourceInfo) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ResourceInfo) GetPresence() *stravaganza.PBElement {
	if x != nil {
		return x.Presence
	}
	return nil
}

var File_proto_c2s_v1_resourceinfo_proto protoreflect.FileDescriptor

const file_proto_c2s_v1_resourceinfo_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/c2s/v1/resourceinfo.proto\x12\x06c2s.v1\x1a4github.com/jackal-xmpp/stravaganza/stravaganza.proto\"\xe8\x01\n" +
	"\fResourceInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x122\n" +
	"\x04info\x18\x03 \x03(\v2\x1e.c2s.v1.ResourceInfo.InfoEntryR\x04info\x122\n" +
	"\bpresence\x18\x04 \x01(\v2\x16.stravaganza.PBElementR\bpresence\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\fZ\n" +
	"pkg/c2s/pbb\x06proto3"

var (
	file_proto_c2s_v1_resourceinfo_proto_rawDescOnce sync.Once
	file_proto_c2s_v1_resourceinfo_proto_rawDescData []byte
)

func file_proto_c2s_v1_resourceinfo_proto_rawDescGZIP() []byte {
	file_proto_c2s_v1_resourceinfo_proto_rawDescOnce.Do(func() {
		file_proto_c2s_v1_resourceinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_c2s_v1_resourceinfo_proto_rawDesc), len(file_proto_c2s_v1_resourceinfo_proto_rawDesc)))
	})
	return file_proto_c2s_v1_resourceinfo_proto_rawDescData
}

var file_proto_c2s_v1_resourceinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_c2s_v1_resourceinfo_proto_goTypes = []any{
	(*ResourceInfo)(nil),          // 0: c2s.v1.ResourceInfo
	nil,                           // 1: c2s.v1.ResourceInfo.InfoEntry
	(*stravaganza.PBElement)(nil), // 2: stravaganza.PBElement
}
var file_proto_c2s_v1_resourceinfo_proto_depIdxs = []int32{
	1, // 0: c2s.v1.ResourceInfo.info:type_name -> c2s.v1.ResourceInfo.InfoEntry
	2, // 1: c2s.v1.ResourceInfo.presence:type_name -> stravaganza.PBElement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_c2s_v1_resourceinfo_proto_init() }
func file_proto_c2s_v1_resourceinfo_proto_init() {
	if File_proto_c2s_v1_resourceinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_c2s_v1_resourceinfo_proto_rawDesc), len(file_proto_c2s_v1_resourceinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_c2s_v1_resourceinfo_proto_goTypes,
		DependencyIndexes: file_proto_c2s_v1_resourceinfo_proto_depIdxs,
		MessageInfos:      file_proto_c2s_v1_resourceinfo_proto_msgTypes,
	}.Build()
	File_proto_c2s_v1_resourceinfo_proto = out.File
	file_proto_c2s_v1_resourceinfo_proto_goTypes = nil
	file_proto_c2s_v1_resourceinfo_proto_depIdxs = nil
}
