// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/archive.proto

package archivemodel

import (
	stravaganza "github.com/jackal-xmpp/stravaganza"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents an archive message entity.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// archived_id is the message archive identifier.
	ArchiveId string `protobuf:"bytes,1,opt,name=archive_id,json=archiveId,proto3" json:"archive_id,omitempty"`
	// id is the message archive unique identifier.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// from_jid is the message from jid value.
	FromJid string `protobuf:"bytes,3,opt,name=from_jid,json=fromJid,proto3" json:"from_jid,omitempty"`
	// to_jid is the message from jid value.
	ToJid string `protobuf:"bytes,4,opt,name=to_jid,json=toJid,proto3" json:"to_jid,omitempty"`
	// message is the archived message.
	Message *stravaganza.PBElement `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// stamp is the timestamp in which the message was archived.
	Stamp         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=stamp,proto3" json:"stamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_model_v1_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_archive_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetFromJid() string {
	if x != nil {
		return x.FromJid
	}
	return ""
}

func (x *Message) GetToJid() string {
	if x != nil {
		return x.ToJid
	}
	return ""
}

func (x *Message) GetMessage() *stravaganza.PBElement {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

// Messages represents a set of archive messages.
type Messages struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArchiveMessages []*Message             `protobuf:"bytes,1,rep,name=archive_messages,json=archiveMessages,proto3" json:"archive_messages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_proto_model_v1_archive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_archive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_archive_proto_rawDescGZIP(), []int{1}
}

func (x *Messages) GetArchiveMessages() []*Message {
	if x != nil {
		return x.ArchiveMessages
	}
	return nil
}

// Metadata represents an archive metadata information.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_timestamp is the identifier of the first archive message.
	StartId string `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	// start_timestamp is the timestamp value of the first archive message.
	StartTimestamp string `protobuf:"bytes,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	// end_id is the identifier of the last archive message.
	EndId string `protobuf:"bytes,3,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	// end_timestamp is the timestamp value of the last archive message.
	EndTimestamp  string `protobuf:"bytes,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_model_v1_archive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_archive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_archive_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetStartId() string {
	if x != nil {
		return x.StartId
	}
	return ""
}

func (x *Metadata) GetStartTimestamp() string {
	if x != nil {
		return x.StartTimestamp
	}
	return ""
}

func (x *Metadata) GetEndId() string {
	if x != nil {
		return x.EndId
	}
	return ""
}

func (x *Metadata) GetEndTimestamp() string {
	if x != nil {
		return x.EndTimestamp
	}
	return ""
}

// Filters define a set of filters to be applied when fetching archive messages.
type Filters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start is used to filter out messages before a certain date/time.
	Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// end is used to filter out messages after a certain date/time.
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	// with contains a JID against which to match messages.
	With string `protobuf:"bytes,3,opt,name=with,proto3" json:"with,omitempty"`
	// before_id is the id of the newest message user wants to fetch.
	BeforeId string `protobuf:"bytes,4,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	// after_id is the id of the oldest message user wants to fetch.
	AfterId string `protobuf:"bytes,5,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	// ids contains one or more ids the user wants to fetch.
	Ids           []string `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_proto_model_v1_archive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_archive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_archive_proto_rawDescGZIP(), []int{3}
}

func (x *Filters) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Filters) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Filters) GetWith() string {
	if x != nil {
		return x.With
	}
	return ""
}

func (x *Filters) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

func (x *Filters) GetAfterId() string {
	if x != nil {
		return x.AfterId
	}
	return ""
}

func (x *Filters) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_model_v1_archive_proto protoreflect.FileDescriptor

const file_proto_model_v1_archive_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/model/v1/archive.proto\x12\x10model.archive.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a4github.com/jackal-xmpp/stravaganza/stravaganza.proto\"\xce\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"archive_id\x18\x01 \x01(\tR\tarchiveId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\bfrom_jid\x18\x03 \x01(\tR\afromJid\x12\x15\n" +
	"\x06to_jid\x18\x04 \x01(\tR\x05toJid\x120\n" +
	"\amessage\x18\x05 \x01(\v2\x16.stravaganza.PBElementR\amessage\x120\n" +
	"\x05stamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\"P\n" +
	"\bMessages\x12D\n" +
	"\x10archive_messages\x18\x01 \x03(\v2\x19.model.archive.v1.MessageR\x0farchiveMessages\"\x8a\x01\n" +
	"\bMetadata\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\tR\astartId\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\tR\x0estartTimestamp\x12\x15\n" +
	"\x06end_id\x18\x03 \x01(\tR\x05endId\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\tR\fendTimestamp\"\xc7\x01\n" +
	"\aFilters\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x12\n" +
	"\x04with\x18\x03 \x01(\tR\x04with\x12\x1b\n" +
	"\tbefore_id\x18\x04 \x01(\tR\bbeforeId\x12\x19\n" +
	"\bafter_id\x18\x05 \x01(\tR\aafterId\x12\x10\n" +
	"\x03ids\x18\x06 \x03(\tR\x03idsB!Z\x1fpkg/model/archive/;archivemodelb\x06proto3"

var (
	file_proto_model_v1_archive_proto_rawDescOnce sync.Once
	file_proto_model_v1_archive_proto_rawDescData []byte
)

func file_proto_model_v1_archive_proto_rawDescGZIP() []byte {
	file_proto_model_v1_archive_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_archive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_archive_proto_rawDesc), len(file_proto_model_v1_archive_proto_rawDesc)))
	})
	return file_proto_model_v1_archive_proto_rawDescData
}

var file_proto_model_v1_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_model_v1_archive_proto_goTypes = []any{
	(*Message)(nil),               // 0: model.archive.v1.Message
	(*Messages)(nil),              // 1: model.archive.v1.Messages
	(*Metadata)(nil),              // 2: model.archive.v1.Metadata
	(*Filters)(nil),               // 3: model.archive.v1.Filters
	(*stravaganza.PBElement)(nil), // 4: stravaganza.PBElement
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_model_v1_archive_proto_depIdxs = []int32{
	4, // 0: model.archive.v1.Message.message:type_name -> stravaganza.PBElement
	5, // 1: model.archive.v1.Message.stamp:type_name -> google.protobuf.Timestamp
	0, // 2: model.archive.v1.Messages.archive_messages:type_name -> model.archive.v1.Message
	5, // 3: model.archive.v1.Filters.start:type_name -> google.protobuf.Timestamp
	5, // 4: model.archive.v1.Filters.end:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_model_v1_archive_proto_init() }
func file_proto_model_v1_archive_proto_init() {
	if File_proto_model_v1_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_archive_proto_rawDesc), len(file_proto_model_v1_archive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_archive_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_archive_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_archive_proto_msgTypes,
	}.Build()
	File_proto_model_v1_archive_proto = out.File
	file_proto_model_v1_archive_proto_goTypes = nil
	file_proto_model_v1_archive_proto_depIdxs = nil
}
