// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/roster.proto

package rostermodel

import (
	stravaganza "github.com/jackal-xmpp/stravaganza"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item represents a roster item entity.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Jid           string                 `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subscription  string                 `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Ask           bool                   `protobuf:"varint,5,opt,name=ask,proto3" json:"ask,omitempty"`
	Groups        []string               `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Item) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Item) GetAsk() bool {
	if x != nil {
		return x.Ask
	}
	return false
}

func (x *Item) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

// Items represent a set of roster items.
type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{1}
}

func (x *Items) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// Notification represents a roster subscription pending notification.
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       string                 `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	Jid           string                 `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	Presence      *stravaganza.PBElement `protobuf:"bytes,3,opt,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Notification) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *Notification) GetPresence() *stravaganza.PBElement {
	if x != nil {
		return x.Presence
	}
	return nil
}

// Notifications represents a set of roster notifications.
type Notifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{3}
}

func (x *Notifications) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// Groups represents a set of roster groups.
type Groups struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []string               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Groups) Reset() {
	*x = Groups{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Groups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Groups) ProtoMessage() {}

func (x *Groups) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Groups.ProtoReflect.Descriptor instead.
func (*Groups) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{4}
}

func (x *Groups) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

// Version represents a roster version number.
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_model_v1_roster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_roster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_roster_proto_rawDescGZIP(), []int{5}
}

func (x *Version) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_model_v1_roster_proto protoreflect.FileDescriptor

const file_proto_model_v1_roster_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/model/v1/roster.proto\x12\x0fmodel.roster.v1\x1a4github.com/jackal-xmpp/stravaganza/stravaganza.proto\"\x96\x01\n" +
	"\x04Item\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03jid\x18\x02 \x01(\tR\x03jid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\fsubscription\x18\x04 \x01(\tR\fsubscription\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\bR\x03ask\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\"4\n" +
	"\x05Items\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.model.roster.v1.ItemR\x05items\"n\n" +
	"\fNotification\x12\x18\n" +
	"\acontact\x18\x01 \x01(\tR\acontact\x12\x10\n" +
	"\x03jid\x18\x02 \x01(\tR\x03jid\x122\n" +
	"\bpresence\x18\x03 \x01(\v2\x16.stravaganza.PBElementR\bpresence\"T\n" +
	"\rNotifications\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.model.roster.v1.NotificationR\rnotifications\" \n" +
	"\x06Groups\x12\x16\n" +
	"\x06groups\x18\x01 \x03(\tR\x06groups\"#\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversionB\x1fZ\x1dpkg/model/roster/;rostermodelb\x06proto3"

var (
	file_proto_model_v1_roster_proto_rawDescOnce sync.Once
	file_proto_model_v1_roster_proto_rawDescData []byte
)

func file_proto_model_v1_roster_proto_rawDescGZIP() []byte {
	file_proto_model_v1_roster_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_roster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_roster_proto_rawDesc), len(file_proto_model_v1_roster_proto_rawDesc)))
	})
	return file_proto_model_v1_roster_proto_rawDescData
}

var file_proto_model_v1_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_model_v1_roster_proto_goTypes = []any{
	(*Item)(nil),                  // 0: model.roster.v1.Item
	(*Items)(nil),                 // 1: model.roster.v1.Items
	(*Notification)(nil),          // 2: model.roster.v1.Notification
	(*Notifications)(nil),         // 3: model.roster.v1.Notifications
	(*Groups)(nil),                // 4: model.roster.v1.Groups
	(*Version)(nil),               // 5: model.roster.v1.Version
	(*stravaganza.PBElement)(nil), // 6: stravaganza.PBElement
}
var file_proto_model_v1_roster_proto_depIdxs = []int32{
	0, // 0: model.roster.v1.Items.items:type_name -> model.roster.v1.Item
	6, // 1: model.roster.v1.Notification.presence:type_name -> stravaganza.PBElement
	2, // 2: model.roster.v1.Notifications.notifications:type_name -> model.roster.v1.Notification
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_model_v1_roster_proto_init() }
func file_proto_model_v1_roster_proto_init() {
	if File_proto_model_v1_roster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_roster_proto_rawDesc), len(file_proto_model_v1_roster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_roster_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_roster_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_roster_proto_msgTypes,
	}.Build()
	File_proto_model_v1_roster_proto = out.File
	file_proto_model_v1_roster_proto_goTypes = nil
	file_proto_model_v1_roster_proto_depIdxs = nil
}
