// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/caps.proto

package capsmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capabilities represents presence capabilities info.
type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Ver           string                 `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_proto_model_v1_caps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_caps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_caps_proto_rawDescGZIP(), []int{0}
}

func (x *Capabilities) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Capabilities) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *Capabilities) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_proto_model_v1_caps_proto protoreflect.FileDescriptor

const file_proto_model_v1_caps_proto_rawDesc = "" +
	"\n" +
	"\x19proto/model/v1/caps.proto\x12\rmodel.caps.v1\"P\n" +
	"\fCapabilities\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeaturesB\x1bZ\x19pkg/model/caps/;capsmodelb\x06proto3"

var (
	file_proto_model_v1_caps_proto_rawDescOnce sync.Once
	file_proto_model_v1_caps_proto_rawDescData []byte
)

func file_proto_model_v1_caps_proto_rawDescGZIP() []byte {
	file_proto_model_v1_caps_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_caps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_caps_proto_rawDesc), len(file_proto_model_v1_caps_proto_rawDesc)))
	})
	return file_proto_model_v1_caps_proto_rawDescData
}

var file_proto_model_v1_caps_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_v1_caps_proto_goTypes = []any{
	(*Capabilities)(nil), // 0: model.caps.v1.Capabilities
}
var file_proto_model_v1_caps_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_v1_caps_proto_init() }
func file_proto_model_v1_caps_proto_init() {
	if File_proto_model_v1_caps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_caps_proto_rawDesc), len(file_proto_model_v1_caps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_caps_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_caps_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_caps_proto_msgTypes,
	}.Build()
	File_proto_model_v1_caps_proto = out.File
	file_proto_model_v1_caps_proto_goTypes = nil
	file_proto_model_v1_caps_proto_depIdxs = nil
}
