// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/admin/v1/users.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUserRequest is the parameter message for CreateUser rpc.
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username defines new created user name.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password is the user desired password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// CreateUserResponse is the response returned by CreateUser rpc.
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{1}
}

// ChangeUserPasswordRequest is the parameter message for ChangeUserPassword rpc.
type ChangeUserPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the name of the user to whom we want to change the password.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// new_password is the new desired password.
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordRequest) Reset() {
	*x = ChangeUserPasswordRequest{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordRequest) ProtoMessage() {}

func (x *ChangeUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeUserPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChangeUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse is the response returned by ChangeUserPassword rpc.
type ChangeUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordResponse) Reset() {
	*x = ChangeUserPasswordResponse{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordResponse) ProtoMessage() {}

func (x *ChangeUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{3}
}

// DeleteUserRequest is the parameter message for DeleteUser rpc.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username defines the username we want to delete.
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// DeleteUserResponse is the response returned by DeleteUser rpc.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_admin_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_users_proto_rawDescGZIP(), []int{5}
}

var File_proto_admin_v1_users_proto protoreflect.FileDescriptor

const file_proto_admin_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/admin/v1/users.proto\x12\badmin.v1\"K\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x14\n" +
	"\x12CreateUserResponse\"Z\n" +
	"\x19ChangeUserPasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x1c\n" +
	"\x1aChangeUserPasswordResponse\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x14\n" +
	"\x12DeleteUserResponse2\xfa\x01\n" +
	"\x05Users\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.admin.v1.CreateUserRequest\x1a\x1c.admin.v1.CreateUserResponse\x12_\n" +
	"\x12ChangeUserPassword\x12#.admin.v1.ChangeUserPasswordRequest\x1a$.admin.v1.ChangeUserPasswordResponse\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.admin.v1.DeleteUserRequest\x1a\x1c.admin.v1.DeleteUserResponseB\x0eZ\fpkg/admin/pbb\x06proto3"

var (
	file_proto_admin_v1_users_proto_rawDescOnce sync.Once
	file_proto_admin_v1_users_proto_rawDescData []byte
)

func file_proto_admin_v1_users_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_users_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_v1_users_proto_rawDesc), len(file_proto_admin_v1_users_proto_rawDesc)))
	})
	return file_proto_admin_v1_users_proto_rawDescData
}

var file_proto_admin_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_admin_v1_users_proto_goTypes = []any{
	(*CreateUserRequest)(nil),          // 0: admin.v1.CreateUserRequest
	(*CreateUserResponse)(nil),         // 1: admin.v1.CreateUserResponse
	(*ChangeUserPasswordRequest)(nil),  // 2: admin.v1.ChangeUserPasswordRequest
	(*ChangeUserPasswordResponse)(nil), // 3: admin.v1.ChangeUserPasswordResponse
	(*DeleteUserRequest)(nil),          // 4: admin.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 5: admin.v1.DeleteUserResponse
}
var file_proto_admin_v1_users_proto_depIdxs = []int32{
	0, // 0: admin.v1.Users.CreateUser:input_type -> admin.v1.CreateUserRequest
	2, // 1: admin.v1.Users.ChangeUserPassword:input_type -> admin.v1.ChangeUserPasswordRequest
	4, // 2: admin.v1.Users.DeleteUser:input_type -> admin.v1.DeleteUserRequest
	1, // 3: admin.v1.Users.CreateUser:output_type -> admin.v1.CreateUserResponse
	3, // 4: admin.v1.Users.ChangeUserPassword:output_type -> admin.v1.ChangeUserPasswordResponse
	5, // 5: admin.v1.Users.DeleteUser:output_type -> admin.v1.DeleteUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_users_proto_init() }
func file_proto_admin_v1_users_proto_init() {
	if File_proto_admin_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_v1_users_proto_rawDesc), len(file_proto_admin_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_v1_users_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_users_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_users_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_users_proto = out.File
	file_proto_admin_v1_users_proto_goTypes = nil
	file_proto_admin_v1_users_proto_depIdxs = nil
}
