// Copyright 2022 The jackal Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/model/v1/last.proto

package lastmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Last represents a user last activity entity.
type Last struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Seconds       int64                  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Last) Reset() {
	*x = Last{}
	mi := &file_proto_model_v1_last_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Last) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Last) ProtoMessage() {}

func (x *Last) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_v1_last_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Last.ProtoReflect.Descriptor instead.
func (*Last) Descriptor() ([]byte, []int) {
	return file_proto_model_v1_last_proto_rawDescGZIP(), []int{0}
}

func (x *Last) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Last) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Last) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_model_v1_last_proto protoreflect.FileDescriptor

const file_proto_model_v1_last_proto_rawDesc = "" +
	"\n" +
	"\x19proto/model/v1/last.proto\x12\rmodel.last.v1\"T\n" +
	"\x04Last\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aseconds\x18\x02 \x01(\x03R\aseconds\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusB\x1bZ\x19pkg/model/last/;lastmodelb\x06proto3"

var (
	file_proto_model_v1_last_proto_rawDescOnce sync.Once
	file_proto_model_v1_last_proto_rawDescData []byte
)

func file_proto_model_v1_last_proto_rawDescGZIP() []byte {
	file_proto_model_v1_last_proto_rawDescOnce.Do(func() {
		file_proto_model_v1_last_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_v1_last_proto_rawDesc), len(file_proto_model_v1_last_proto_rawDesc)))
	})
	return file_proto_model_v1_last_proto_rawDescData
}

var file_proto_model_v1_last_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_v1_last_proto_goTypes = []any{
	(*Last)(nil), // 0: model.last.v1.Last
}
var file_proto_model_v1_last_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_v1_last_proto_init() }
func file_proto_model_v1_last_proto_init() {
	if File_proto_model_v1_last_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_v1_last_proto_rawDesc), len(file_proto_model_v1_last_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_v1_last_proto_goTypes,
		DependencyIndexes: file_proto_model_v1_last_proto_depIdxs,
		MessageInfos:      file_proto_model_v1_last_proto_msgTypes,
	}.Build()
	File_proto_model_v1_last_proto = out.File
	file_proto_model_v1_last_proto_goTypes = nil
	file_proto_model_v1_last_proto_depIdxs = nil
}
